
modLoader="javafml"

loaderVersion="[40,)"

license="All rights reserved"

[[mods]]

modId="darkeststress"
version="1.1"
displayName="Darkest Stress"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="darkeststress.png"
#credits="Yes :]" #optional
authors="Purplik"

#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description='''
Mod that aims to add stress into the game for more careful player management while taking inspiration from Darkest Dungeon and Thaumcraft.
'''

[[dependencies.darkeststress]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.darkeststress]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"